config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  
  root 'home#index'

  resources :phones
  resources :adresses
  resources :contacts
  resources :kinds

end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: [:show, :edit, :update, :destroy]

  # GET /adresses
  # GET /adresses.json
  def index
    @adresses = Adress.all
  end

  # GET /adresses/1
  # GET /adresses/1.json
  def show
  end

  # GET /adresses/new
  def new
    @adress = Adress.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses
  # POST /adresses.json
  def create
    @adress = Adress.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress, notice: 'Adress was successfully created.' }
        format.json { render :show, status: :created, location: @adress }
      else
        format.html { render :new }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adresses/1
  # PATCH/PUT /adresses/1.json
  def update
    respond_to do |format|
      if @adress.update(adress_params)
        format.html { redirect_to @adress, notice: 'Adress was successfully updated.' }
        format.json { render :show, status: :ok, location: @adress }
      else
        format.html { render :edit }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adresses/1
  # DELETE /adresses/1.json
  def destroy
    @adress.destroy
    respond_to do |format|
      format.html { redirect_to adresses_url, notice: 'Adress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adress_params
      params.require(:adress).permit(:street, :city, :state, :contact_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/views/adresses/_form.html.erb
<%= form_for(@adress, html: { class: "basic-grey"}) do |f| %>
  <% if @adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% @adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Endereços</h1>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", class: "button" %>
    <%= link_to 'Voltar', contacts_path, class: "button" %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<h1>Editing Adress</h1>

<%= render 'form' %>

<%= link_to 'Show', @adress %> |
<%= link_to 'Back', adresses_path %>

app/views/adresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adresses.each do |adress| %>
      <tr>
        <td><%= adress.street %></td>
        <td><%= adress.city %></td>
        <td><%= adress.state %></td>
        <td><%= adress.contact %></td>
        <td><%= link_to 'Show', adress %></td>
        <td><%= link_to 'Edit', edit_adress_path(adress) %></td>
        <td><%= link_to 'Destroy', adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adress', new_adress_path %>

app/views/adresses/new.html.erb
<%= render 'form' %>

app/views/adresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @adress.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @adress.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @adress.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @adress.contact %>
</p>

<%= link_to 'Edit', edit_adress_path(@adress) %> |
<%= link_to 'Back', adresses_path %>